# Generated by Django 4.1.7 on 2023-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capabilities_needed', models.CharField(max_length=100)),
                ('disease_area', models.CharField(max_length=100)),
                ('study_type', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
